### PR TITLE
 🏗 Setup a GitHub Action using Gradle to run the unit tests #2 

### PR DESCRIPTION
**Pull request by jmfayard**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

A GitHub Action for Gradle that runs the unit test of this Android project

## Related Tickets & Documents

GitHub Actions hackaton on DEV

https://dev.to/devteam/announcing-the-github-actions-hackathon-on-dev-3ljn

## Screenshots/Recordings (if there are UI changes)

See https://github.com/jmfayard/DEV-Android/actions?query=workflow%3A%22Android+unit+tests%22

I added the build scan plugin for better reporting if there are tests failure

https://scans.gradle.com/s/2tzis4ikslecg/tests

Build_scan_for__DEV-Android__just_now___Gradle_Cloud_Services_and_DEV-Android____StudioProjects_DEV-Android__-_____app_src_test_java_to_dev_dev_android_view_main_view_MainActivityTest_kt__app_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by SGGregory** [comment]
Hey @jmfayard! This is awesome. Just wanted to let you know that we do require GitHub Actions Hackathon participants to write a post about their workflow/action on DEV to have a valid submission. The template for this post is [here](https://dev.to/new/actionshackathon) and more info on the hackathon is [here](https://dev.to/devteam/announcing-the-github-actions-hackathon-on-dev-3ljn). Thanks! These posts are due by September 17th by 11:59 PM PT :)

**Comment by jmfayard** [comment]
I know, let see if I manage to write tomorrow :)

Le mar. 15 sept. 2020 à 21:34, Gracie Gregory <notifications@github.com> a
écrit :

**Comment by jmfayard** [comment]
My article is now available here
https://dev.to/jmfayard/how-do-i-setup-github-actions-for-my-gradle-or-android-project-3eal

**Comment by SGGregory** [comment]
Awesome!

**Review by fdoxyz — APPROVED** [review]
This is a very valuable contribution, thanks a lot @jmfayard!

head bang

Just as a note: I wanted to give it a few days to hear from the team internally (about their opinions on Actions vs other CI solutions) but it slipped from my radar a bit longer than I wanted to. Anyways, sorry for taking a bit to accept. Really appreciate it!

**Pull request merged**
