### PR TITLE
Add methods to implement native copy-to-clipboard functionality.

### PR DESCRIPTION
**Pull request by VarunBarad**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description
This PR adds the native methods required to invoke the platform specific "copy url to clipboard" function.

To complete the integration, some code needs to be added to the [https://dev.to](https://dev.to) also. Will create an issue for that over on [`thepracticaldev/dev.to`](https://github.com/thepracticaldev/dev.to) with specific instructions as to what changes need to be made.

**Issue with instructions for website**: [https://github.com/thepracticaldev/dev.to/issues/4543](https://github.com/thepracticaldev/dev.to/issues/4543)

## Related Tickets & Documents
#58

### CODE REVIEW

**Comment by VarunBarad** [comment]
@maestromac Can you check what is wrong with the `license/cla` check?
I have previously contributed to this repo and therefore have already agreed to the CLA. But for some reason here the `license/cla` check just isn't passing.

**Comment by VarunBarad** [comment]
@maestromac any help required?

**Comment by maestromac** [comment]
Thank you again @VarunBarad and I apologize for not getting to this sooner. 🙇 

This turns out to be everything we wanted but we got sidetracked and ended up [re-doing the same thing](https://github.com/thepracticaldev/DEV-Android/pull/70). That said, we would like to take over this PR; to resolve to merge conflict and to include your "toast" implementation. Please let us know what you think.

**Comment by VarunBarad** [comment]
Please go ahead and include whatever you want, always happy to help 🙂 
I only have one request, in the currently merged implementation of `AndroidWebViewBridge` the Context property is named `mContext`. Can you please rename it to `context` as hungarian notation is not advisable.

**Pull request merged**
