### PR TITLE
Implement initial base classes, webView & icon

### PR DESCRIPTION
**Pull request by luchfilip**
I've thought it would be nice to have someone start the android app as well, especially that it's all mainly done on webView. 

Based on the links in the readme file, it seems like everything has to be in a webview. 

Key points:
- package name: `to.dev.devto.android`
- Kotlin
- Android min SDK version 19
- empty base navigator & viewModel 
- BaseActivity which handles the DataBinding for now
- Dev.to icon
- one MainActivity which sets up the webView and loads the base `https://dev.to` URL

The purpose of this PR is mostly to start the discussion on how is it expected to be done and to get it in that state if necessary.

### CODE REVIEW

**Comment by luchfilip** [comment]
@benhalpern do you think it still makes sense to have the android app?

**Comment by shubh10** [comment]
If we are going to have an Android app it will make more sense to have completely native app, not simply webviews since the PWA on Android pretty much achieved that.

**Comment by luchfilip** [comment]
Native app seems to be overkill. Especially that so much effort has been put into making the app work well on various screen sizes. Also, long term it is hard to keep them in sync. So if there is no need for a native app then I don't see why we'd build one. The reason I'd think it makes sense to have a native app wrap a webview is to have a presence on google play store & maybe handle other native parts in future. Might be nativation, search, state management.

**Comment by maestromac** [comment]
Sorry for being super late to this @luchfilip . We're finally ready to start this and we really appreciate your PR; it is really inline of what we plan to do. I went ahead and set up a barebone app. If you want to break down things you did into a new PR, we're happy to review it.

**Comment by filipuic** [comment]
Sounds good. Let me pull the base and work off of that.

**Pull request closed without merging**
